version: 2

docker_login: &docker_login
  run:
    name: authentication
    command: |
      docker --version
      docker-compose --version
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
cargo_login: &cargo_login
  run:
    name: authentication
    command:  |
      cargo --version
      cargo login "$CARGO_TOKEN"

workflows:
  version: 2
  flow:
    jobs:
      - test
      - musl_build
      - docker_push:
          requires:
            - test
            - musl_build
          filters:
            branches:
              only:
                - master
      - cargo_publish:
          requires:
            - test
            - musl_build
          filters:
            branches:
              only:
                - master
jobs:
  test:
    docker:
      - image: clux/muslrust
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          keys:
          - cargo.registry-{{ checksum "Cargo.lock" }}
          - cargo.registry-
      - restore_cache:
          keys:
          - target-{{ checksum "Cargo.lock" }}
          - target-
      - run: cargo test
  musl_build:
    docker:
      - image: clux/muslrust
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          keys:
          - cargo.registry-{{ checksum "Cargo.lock" }}
          - cargo.registry-
      - restore_cache:
          keys:
          - target-{{ checksum "Cargo.lock" }}
          - target-
      - run: cargo build --release
      - save_cache:
          key: target-{{ checksum "Cargo.lock" }}
          paths:
            - target
      - save_cache:
          key: cargo.registry-{{ checksum "Cargo.lock" }}
          paths:
            - /root/.cargo
      - persist_to_workspace:
          root: target/x86_64-unknown-linux-musl/release/
          paths:
            - md-toc
  docker_push:
    machine:
      enabled: true
      docker_layer_caching: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - <<: *docker_login
      - run: make tag-latest
      - run: make tag-semver
  cargo_publish:
    docker:
      - image: clux/muslrust
    working_directory: /volume
    steps:
      - checkout
      - restore_cache:
          keys:
          - cargo.registry-{{ checksum "Cargo.lock" }}
          - cargo.registry-
      - restore_cache:
          keys:
          - target-{{ checksum "Cargo.lock" }}
          - target-
      - <<: *cargo_login
      - run: curl -sSL https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 --output /usr/bin/jq
      - run: chmod +x /usr/bin/jq
      - run: make cargo-publish
